name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: CFC-Servers/gmod-upload@master
        with:
          id: 3130830097
          changelog: "Deployment via Github to latest changes, [url=https://github.com/EntranceJew/ttt2_ticket_muncher/commits/main/]see here[/url]"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
